---
model: "BCS-UNet"
bcs: True

data_module:
  data_dir: "../input"
  batch_size: 64
  val_percent: 0.1
  num_workers: 0

net:
  upsamplenet:
    init_type: "xavier"
    out_channels_1: 16
    out_channels_2: 8
    use_transpose_conv: False
    spectral_norm: True
  unet:
    init_type: "xavier"
    channels: 16
    use_dropout: True

learner:
  intermediate_image: True
  criterion: "L1" 
  val_metrics: ["psnr"]
  test_metrics: ["psnr", "ssim"] 
  lr: 0.001
  weight_decay: 0.0
  scheduler:
    type: "reduce_lr_on_plateau"  # or "one_cycle"
    args_reduce_lr_on_plateau:
      factor: 0.3
      patience: 2
      verbose: True
    arg_one_cycle:
      pct_start: 0.3
      verbose: True

callbacks:
  checkpoint:
    monitor: "val_loss"
    save_last: True
    filename: "best"
  early_stopping:
    monitor: "val_loss"
    patience: 6

trainer:
  epochs: 50
  gpu: 1
  fp16: True
