---
num_classes: 10

data_module:
  data_dir: "C:/DL/Datasets/imagewoof"
  csv_path: "C:/DL/Datasets/imagewoof/noisy_imagewoof.csv"
  fold: None
  batch_size: 32

transforms:
  image_size: 128
  transpose: 0.5
  hflip: 0.5
  vflip: 0.5
  brightness:
    limit: 0.2
    p: 0.75
  contrast:
    limit: 0.2
    p: 0.75
  center_crop: 1.0

net:
  arch: 

learner:
  criterion: "cross_entropy"  # need to configure a dispatcher
  metrics: ["accuracy"]  # need to configure a dispatcher
  lr: 0.001
  weight_decay: 0.01
  scheduler:
    type: "reduce_lr_on_plateau"  # or "one_cycle"
    args_reduce_lr_on_plateau:
      factor: 0.3
      patience: 3
      verbose: True
    arg_one_cycle:
      pct_start: 0.3
      verbose: True

callbacks:
  checkpoint:
    monitor: "valid_loss"
    save_last: True
  early_stopping:
    monitor: "valid_loss"
    patience: 10

trainer:
  epochs: 1
  gpu: 1
  