---
# This yaml file has the configurations for inference.

gpu: True
checkpoint_path: "../logs/BCS-UNet_STL10_1875/best/checkpoints/best.ckpt"
sampling_ratio: 0.1875
measurement_matrix: "../input/phi_block_binary.npy"
real_data:
  - filename: "G_1875.mat" # "G_1250.mat"
    min: 0.001 # 0.001
    max: 0.12 # 0.0163
  - filename: "H_1875.mat"
    min: 0.001
    max: 0.13
