---
# This yaml file has the configurations for inference.
# Not dependent on the main config file.

gpu: 1  # change to 0 if use cpu
checkpoint_path: "../lightning_logs/version_38/checkpoints/last.ckpt"
test_mode: True  # TODO: deprecate this feature later because no need to test anymore
measurement_matrix: "../input/phi_block_binary.npy"
sampling_ratio: 0.125
real_data:  # TODO: maybe need a better name?
  - filename: "G_1250.mat"
    min: 0.001
    max: 0.0163
  - filename: "H_1250.mat"
    min: 0.0
    max: 0.0184
